version: "3"

services:
  nuxt:
    image: registry.gitlab.com/pmoreira/nuxt-norris-jokes:latest
    build: .
    container_name: nuxt
    restart: always
    # ports:
    #   - "3000:5000"
    command:
      "npm run start"
    depends_on:
      - nginx

  nginx:
    image: nginx:1.13
    container_name: nginx
    restart: always
    ports:
    #   - "80:80"
      - "443:443"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./nginx/certs:/etc/nginx/certs
